// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnowBack.Models;

#nullable disable

namespace SnowBack.Migrations
{
    [DbContext(typeof(SnowmansContext))]
    [Migration("20250119190821_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SnowBack.Models.DAuthentication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.HasKey("Id");

                    b.ToTable("D_Authentication", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DDfieldsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("description");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("D_DFields_Types", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DEmployeesDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Birth")
                        .HasColumnType("date")
                        .HasColumnName("birth");

                    b.Property<string>("Breast")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("breast");

                    b.Property<string>("Cloth")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cloth");

                    b.Property<string>("Code")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("code");

                    b.Property<string>("Gloves")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("gloves");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Hand")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("hand");

                    b.Property<string>("Head")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("head");

                    b.Property<string>("Height")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("height");

                    b.Property<string>("Mname")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("mname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone");

                    b.Property<string>("Shoes")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("shoes");

                    b.Property<string>("Shortname")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("shortname");

                    b.Property<string>("Sname")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("sname");

                    b.Property<string>("Step")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("step");

                    b.Property<string>("Waist")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("waist");

                    b.HasKey("Id");

                    b.ToTable("D_Employees_Details", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("code");

                    b.Property<DateTime>("DateOn")
                        .HasColumnType("datetime")
                        .HasColumnName("dateOn");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.Property<decimal>("Remain")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("remain");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("D_Goods", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DGoodsInfraRelation", b =>
                {
                    b.Property<int>("Element")
                        .HasColumnType("int")
                        .HasColumnName("element");

                    b.Property<int>("Good")
                        .HasColumnType("int")
                        .HasColumnName("good");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.ToTable("D_Goods_Infra_Relations", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DGoodsKb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Description")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("description");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("filepath");

                    b.Property<Guid?>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<int>("Relatedobject")
                        .HasColumnType("int")
                        .HasColumnName("relatedobject");

                    b.HasKey("Id");

                    b.ToTable("D_Goods_KB", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DGoodsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("D_Goods_Types", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DGroupTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("created");

                    b.Property<int?>("Creator")
                        .HasColumnType("int")
                        .HasColumnName("creator");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("D_Group_Task", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DInfraElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Gps")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("gps");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Inventorycode")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("inventorycode");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("D_Infra_Elements", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DInfraElementsField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Dateon")
                        .HasColumnType("datetime")
                        .HasColumnName("dateon");

                    b.Property<int?>("ElementId")
                        .HasColumnType("int")
                        .HasColumnName("element_id");

                    b.Property<int?>("FieldType")
                        .HasColumnType("int")
                        .HasColumnName("field_type");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.Property<int?>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("FieldType");

                    b.ToTable("D_Infra_Elements_Fields", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DInfraElementsFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.Property<int?>("Objectid")
                        .HasColumnType("int")
                        .HasColumnName("objectid");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("D_Infra_Elements_Functions", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DInfraElementsKb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Description")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("description");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("filepath");

                    b.Property<Guid?>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<int>("Relatedobject")
                        .HasColumnType("int")
                        .HasColumnName("relatedobject");

                    b.HasKey("Id");

                    b.ToTable("D_Infra_Elements_KB", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DInfraElementsParent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("Objectid")
                        .HasColumnType("int")
                        .HasColumnName("objectid");

                    b.Property<int?>("Parentid")
                        .HasColumnType("int")
                        .HasColumnName("parentid");

                    b.HasKey("Id");

                    b.ToTable("D_Infra_Elements_Parents", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DInfraElementsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("D_Infra_Elements_Types", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DKbDoc", b =>
                {
                    b.Property<byte[]>("Description")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("description");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("filepath");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<int>("Relatedobject")
                        .HasColumnType("int")
                        .HasColumnName("relatedobject");

                    b.Property<bool>("Type")
                        .HasColumnType("bit")
                        .HasColumnName("type");

                    b.ToTable("D_KB_Docs", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DPlannedTask", b =>
                {
                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Parenttask")
                        .HasColumnType("int")
                        .HasColumnName("parenttask");

                    b.Property<int>("Task")
                        .HasColumnType("int")
                        .HasColumnName("task");

                    b.ToTable("D_PlannedTasks", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CallId")
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasColumnName("callId")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("email");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("lastname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasColumnName("phone")
                        .IsFixedLength();

                    b.Property<int?>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<string>("Surename")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("surename");

                    b.HasKey("Id");

                    b.ToTable("D_Staff", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DStaffKb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Description")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("description");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("filepath");

                    b.Property<Guid?>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<int>("Relatedobject")
                        .HasColumnType("int")
                        .HasColumnName("relatedobject");

                    b.HasKey("Id");

                    b.ToTable("D_Staff_KB", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("created");

                    b.Property<TimeOnly?>("Duration")
                        .HasColumnType("time")
                        .HasColumnName("duration");

                    b.Property<Guid?>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<int?>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.ToTable("D_Tasks", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DTasksKb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Description")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("description");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("filepath");

                    b.Property<Guid?>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<int>("Relatedobject")
                        .HasColumnType("int")
                        .HasColumnName("relatedobject");

                    b.HasKey("Id");

                    b.ToTable("D_Tasks_KB", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.JElementsState", b =>
                {
                    b.Property<int?>("Element")
                        .HasColumnType("int")
                        .HasColumnName("element");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logfile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logfile");

                    b.Property<int?>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<DateTime>("Status")
                        .HasColumnType("datetime")
                        .HasColumnName("status");

                    b.Property<DateTime>("Statuson")
                        .HasColumnType("datetime")
                        .HasColumnName("statuson");

                    b.Property<int?>("User")
                        .HasColumnType("int")
                        .HasColumnName("user");

                    b.ToTable("J_Elements_States", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.JEmployeesMove", b =>
                {
                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime");

                    b.Property<int>("UserWho")
                        .HasColumnType("int");

                    b.Property<int>("Vehicle")
                        .HasColumnType("int");

                    b.ToTable("J_Employees_Moves", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.JEmployeesSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Deviation")
                        .HasColumnType("int");

                    b.Property<int>("Employee")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<int>("Manager")
                        .HasColumnType("int");

                    b.Property<int?>("Shift")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Variant")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("Employee");

                    b.HasIndex("Shift");

                    b.ToTable("J_Employees_Schedule", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.JGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DelDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("DelUser")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Destination")
                        .HasColumnType("int");

                    b.Property<string>("DestinationAddr")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("Element")
                        .HasColumnType("int");

                    b.Property<int?>("Good")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Remain")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Source")
                        .HasColumnType("int");

                    b.Property<string>("SourceAddr")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("Task")
                        .HasColumnType("int");

                    b.Property<bool>("Type")
                        .HasColumnType("bit");

                    b.Property<int>("UserWho")
                        .HasColumnType("int");

                    b.Property<int?>("UserWhom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("J_Goods", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.JGoodsMoved", b =>
                {
                    b.Property<DateTime>("DateOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("Destination")
                        .HasColumnType("int");

                    b.Property<string>("DestinationAddr")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("Element")
                        .HasColumnType("int");

                    b.Property<int?>("Good")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Source")
                        .HasColumnType("int");

                    b.Property<string>("SourceAddr")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("Task")
                        .HasColumnType("int");

                    b.Property<bool>("Type")
                        .HasColumnType("bit");

                    b.Property<int>("UserWho")
                        .HasColumnType("int");

                    b.Property<int?>("UserWhom")
                        .HasColumnType("int");

                    b.ToTable("J_Goods_Moved", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.JSnowGunsOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Dateon")
                        .HasColumnType("date")
                        .HasColumnName("dateon");

                    b.Property<int?>("Direction")
                        .HasColumnType("int")
                        .HasColumnName("direction");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<int>("GunId")
                        .HasColumnType("int")
                        .HasColumnName("gun_id");

                    b.Property<int?>("MainPoint")
                        .HasColumnType("int")
                        .HasColumnName("main_point");

                    b.Property<int?>("Point")
                        .HasColumnType("int")
                        .HasColumnName("point");

                    b.Property<int?>("Powerline")
                        .HasColumnType("int")
                        .HasColumnName("powerline");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<int?>("Waterline")
                        .HasColumnType("int")
                        .HasColumnName("waterline");

                    b.HasKey("Id");

                    b.ToTable("J_SnowGuns_Orders", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.JStaffAssign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Employee")
                        .HasColumnType("int")
                        .HasColumnName("employee");

                    b.Property<DateOnly?>("Fired")
                        .HasColumnType("date")
                        .HasColumnName("fired");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<DateOnly>("Hired")
                        .HasColumnType("date")
                        .HasColumnName("hired");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("Employee");

                    b.ToTable("J_Staff_Assign", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.JTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int?>("Creator")
                        .HasColumnType("int")
                        .HasColumnName("creator");

                    b.Property<DateTime>("Dateoff")
                        .HasColumnType("datetime")
                        .HasColumnName("dateoff");

                    b.Property<DateTime>("Dateon")
                        .HasColumnType("datetime")
                        .HasColumnName("dateon");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("Element")
                        .HasColumnType("int")
                        .HasColumnName("element");

                    b.Property<string>("Emergency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("emergency")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("Executor")
                        .HasColumnType("int")
                        .HasColumnName("executor");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("groupId");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<bool?>("IsComplete")
                        .HasColumnType("bit")
                        .HasColumnName("isComplete");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("bit")
                        .HasColumnName("isGroup");

                    b.Property<int>("Task")
                        .HasColumnType("int")
                        .HasColumnName("task");

                    b.HasKey("Id");

                    b.ToTable("J_Tasks", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.JTransportFueling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Fuelamount")
                        .HasColumnType("float")
                        .HasColumnName("fuelamount");

                    b.Property<string>("Fueltype")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fueltype");

                    b.Property<int?>("Gasstation")
                        .HasColumnType("int")
                        .HasColumnName("gasstation");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<int?>("Userwho")
                        .HasColumnType("int")
                        .HasColumnName("userwho");

                    b.Property<int>("Vehicle")
                        .HasColumnType("int")
                        .HasColumnName("vehicle");

                    b.HasKey("Id");

                    b.ToTable("J_Transport_Fueling", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.JTransportRent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("Element")
                        .HasColumnType("int")
                        .HasColumnName("element");

                    b.Property<int>("Executor")
                        .HasColumnType("int")
                        .HasColumnName("executor");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("datetime")
                        .HasColumnName("finished");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.Property<int?>("Point")
                        .HasColumnType("int")
                        .HasColumnName("point");

                    b.Property<int?>("Rent")
                        .HasColumnType("int")
                        .HasColumnName("rent");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("datetime")
                        .HasColumnName("started");

                    b.Property<int?>("Task")
                        .HasColumnType("int")
                        .HasColumnName("task");

                    b.HasKey("Id");

                    b.ToTable("J_Transport_Rent", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Shift", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.StaffPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Staff_Position", (string)null);
                });

            modelBuilder.Entity("SnowBack.Models.DInfraElementsField", b =>
                {
                    b.HasOne("SnowBack.Models.DDfieldsType", "FieldTypeNavigation")
                        .WithMany("DInfraElementsFields")
                        .HasForeignKey("FieldType")
                        .HasConstraintName("FK_D_Infra_Elements_Fields_D_DFields_Types");

                    b.Navigation("FieldTypeNavigation");
                });

            modelBuilder.Entity("SnowBack.Models.JEmployeesSchedule", b =>
                {
                    b.HasOne("SnowBack.Models.DStaff", "EmployeeNavigation")
                        .WithMany("JEmployeesSchedules")
                        .HasForeignKey("Employee")
                        .IsRequired()
                        .HasConstraintName("FK_J_Employees_Schedule_D_Staff");

                    b.HasOne("SnowBack.Models.Shift", "ShiftNavigation")
                        .WithMany("JEmployeesSchedules")
                        .HasForeignKey("Shift")
                        .HasConstraintName("FK_J_Employees_Schedule_Shift");

                    b.Navigation("EmployeeNavigation");

                    b.Navigation("ShiftNavigation");
                });

            modelBuilder.Entity("SnowBack.Models.JStaffAssign", b =>
                {
                    b.HasOne("SnowBack.Models.DStaff", "EmployeeNavigation")
                        .WithMany("JStaffAssigns")
                        .HasForeignKey("Employee")
                        .IsRequired()
                        .HasConstraintName("FK_J_Staff_Assign_D_Staff");

                    b.Navigation("EmployeeNavigation");
                });

            modelBuilder.Entity("SnowBack.Models.DDfieldsType", b =>
                {
                    b.Navigation("DInfraElementsFields");
                });

            modelBuilder.Entity("SnowBack.Models.DStaff", b =>
                {
                    b.Navigation("JEmployeesSchedules");

                    b.Navigation("JStaffAssigns");
                });

            modelBuilder.Entity("SnowBack.Models.Shift", b =>
                {
                    b.Navigation("JEmployeesSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
